item {
	name: "A"
	id: 1
}
item {
	name: "B"
	id: 2
}
item {
	name: "D"
	id: 3
}
item {
	name: "L"
	id: 4
}
item {
	name: "O"
	id: 5
}
item {
	name: "U"
	id: 6
}
item {
	name: "W"
	id: 7
}
item {
	name: "Space"
	id: 8
}
item {
	name: "Enter"
	id: 9
}
